### ISSUE TITLE
show the wiki we are connected to

### ISSUE THREAD

**Issue by hashar** [wikimedia/WLMMobile#263]
WLMMobile seems to use test.wikipedia.org per default which led me to upload there instead of on the commons.

Would be nice to show the host we are connected too on the main page as well as in "parameters".

**Comment by jdlrobson** [comment]
yes... this has been a bit of a pain point assets/www/js/config.js is the source of this information. Ideally it would be nice to have a 'switch' for development mode and production mode

**Comment by Krinkle** [comment]
Closing as repo is deprecated, in preparation for archiving.
