### ISSUE TITLE
App doesn't work anymore?

### ISSUE THREAD

**Issue by Mistress-Anna** [wikimedia/WLMMobile#269]
The app cannot find my location, it always ends with an error, be it with gps, wifi or mobile net. The app also fails to propose a country list, the loading never ends, with or without a search term.

It seems other issues on this project are 4 years old. Is the project abandoned? If it is, it should be removed from app repositories because it's rather deceptive.

**Comment by dbrant** [comment]
Correct, this app is no longer supported. Sorry for the confusion; I've added a "deprecated" notice in the repo description.
